-----시퀀스
DROP SEQUENCE "SEQ_GROUP_ID";
CREATE SEQUENCE "SEQ_GROUP_ID";

DROP SEQUENCE "SEQ_BOARD_ID";
CREATE SEQUENCE "SEQ_BOARD_ID" ;

DROP SEQUENCE "SEQ_RECORD_ID";
CREATE SEQUENCE "SEQ_RECORD_ID";

DROP SEQUENCE "SEQ_REPLY_ID";
CREATE SEQUENCE "SEQ_REPLY_ID" ;

DROP SEQUENCE "SEQ_SUBJECT_ID";
CREATE SEQUENCE "SEQ_SUBJECT_ID" ;

-----DROP﻿

DROP TABLE "RECORD";
DROP TABLE "SUBJECT";
DROP TABLE "GROUP_MEMBER";
DROP TABLE "GROUP";
DROP TABLE "BOARD_REPLY";
DROP TABLE "BOARD";
DROP TABLE "MEMBER";



CREATE TABLE "RECORD" (
	"RECORD_ID"	NUMBER		NOT NULL,
	"RECORD_SUBJECT_ID"	NUMBER		NOT NULL,
	"RECORD_MEM_ID"	VARCHAR2(20)		NOT NULL,
	"RECORD_START"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"RECORD_END"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NULL
);

COMMENT ON COLUMN "RECORD"."RECORD_ID" IS '학습기록순서';

COMMENT ON COLUMN "RECORD"."RECORD_SUBJECT_ID" IS '과목 아이디, SEQUENCE';

COMMENT ON COLUMN "RECORD"."RECORD_MEM_ID" IS '과목명이랑 PK';

COMMENT ON COLUMN "RECORD"."RECORD_START" IS '공부시작시간';

COMMENT ON COLUMN "RECORD"."RECORD_END" IS '공부종료시간';



CREATE TABLE "SUBJECT" (
	"SUBJECT_ID"	NUMBER		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"SUBJECT_NAME"	VARCHAR2(20)		NOT NULL,
	"SUBJECT_ADD_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"SUBJECT_DEL_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NULL,
	"SUBJECT_COLOR"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "SUBJECT"."SUBJECT_ID" IS '과목 아이디, SEQUENCE';

COMMENT ON COLUMN "SUBJECT"."MEM_ID" IS '과목명이랑 PK';

COMMENT ON COLUMN "SUBJECT"."SUBJECT_NAME" IS '과목명(사용자 자유설정)';

COMMENT ON COLUMN "SUBJECT"."SUBJECT_ADD_DATE" IS '과목추가시간';

COMMENT ON COLUMN "SUBJECT"."SUBJECT_DEL_DATE" IS '과목삭제시간(과목 삭제 안한게  최대 5개)';

COMMENT ON COLUMN "SUBJECT"."SUBJECT_COLOR" IS '과목 색상 숫자(핑크, 연두 ,노랑, 파랑, 보라)';



CREATE TABLE "MEMBER" (
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_PWD"	VARCHAR2(50)		NOT NULL,
	"MEM_EMAIL"	VARCHAR2(100)		NOT NULL,
	"MEM_RECORD_ING"	CHAR(1)	DEFAULT 0	NOT NULL,
	"MEM_COMMENT"	VARCHAR2(1000)		NULL,
	"MEM_ACTIVE"	CHAR(1)	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEM_ID" IS '영문자, 숫자';

COMMENT ON COLUMN "MEMBER"."MEM_PWD" IS '영문자, 숫자';

COMMENT ON COLUMN "MEMBER"."MEM_EMAIL" IS '이메일';

COMMENT ON COLUMN "MEMBER"."MEM_RECORD_ING" IS '공부중(1), 공부안함(0)';

COMMENT ON COLUMN "MEMBER"."MEM_COMMENT" IS '각오 한마디';

COMMENT ON COLUMN "MEMBER"."MEM_ACTIVE" IS '탈퇴(0), 활동중(1)';



CREATE TABLE "BOARD" (
	"BOARD_ID"	NUMBER		NOT NULL,
	"BOARD_WRITER"	VARCHAR2(20)		NOT NULL,
	"TITLE"	VARCHAR2(120)		NOT NULL,
	"CONTENT"	VARCHAR2(4000)		NOT NULL,
	"WRITE_TIME"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"BOARD_LIKE"	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_ID" IS '게시글번호';

COMMENT ON COLUMN "BOARD"."BOARD_WRITER" IS '게시글 작성자ID';

COMMENT ON COLUMN "BOARD"."TITLE" IS '글제목';

COMMENT ON COLUMN "BOARD"."CONTENT" IS '글내용';

COMMENT ON COLUMN "BOARD"."WRITE_TIME" IS '글작성시간';

COMMENT ON COLUMN "BOARD"."READ_COUNT" IS '조회수';

COMMENT ON COLUMN "BOARD"."BOARD_LIKE" IS '좋아요 수';







CREATE TABLE "BOARD_REPLY" (
	"REPLY_ID"	NUMBER		NOT NULL,
	"BOARD_ID"	NUMBER		NOT NULL,
	"REPLY_WRITER_ID"	VARCHAR2(20)		NOT NULL,
	"REPLY_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"REPLY_WRITE_TIME"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"REPLY_REF"	NUMBER		NULL,
	"REPLY_STEP"	NUMBER(3)	DEFAULT 1	NOT NULL,
	"REPLY_LEVEL"	NUMBER(2)	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "BOARD_REPLY"."REPLY_ID" IS '댓글';

COMMENT ON COLUMN "BOARD_REPLY"."BOARD_ID" IS '댓글 적은 글번호';

COMMENT ON COLUMN "BOARD_REPLY"."REPLY_WRITER_ID" IS '댓글 작성자 아이디';

COMMENT ON COLUMN "BOARD_REPLY"."REPLY_CONTENT" IS '댓글내용';

COMMENT ON COLUMN "BOARD_REPLY"."REPLY_WRITE_TIME" IS '댓글작성시간';

COMMENT ON COLUMN "BOARD_REPLY"."REPLY_REF" IS '최초 댓글의 번호, BOARD_REPLY_ID';

COMMENT ON COLUMN "BOARD_REPLY"."REPLY_STEP" IS '최초 댓글 기준으로 몇 번째인지';

COMMENT ON COLUMN "BOARD_REPLY"."REPLY_LEVEL" IS '댓글, 대댓글, 대대댓글';






CREATE TABLE "GROUP" (
	"GROUP_ID"	NUMBER		NOT NULL,
	"GROUP_NAME"	CHAR(30)		NOT NULL,
	"GROUP_OPEN"	CHAR(1)	DEFAULT 0	NOT NULL,
	"GROUP_PWD"	NUMBER		NULL,
	"GROUP_EXPLAIN"	VARCHAR2(4000)		NULL,
	"GROUP_IMG_PATH"	VARCHAR2(1000)		NULL,
	"GROUP_IMG_NAME"	VARCHAR2(200)		NULL
);

COMMENT ON COLUMN "GROUP"."GROUP_ID" IS '그룹 아이디, SEQUENCE';

COMMENT ON COLUMN "GROUP"."GROUP_NAME" IS 'UNIQUE';

COMMENT ON COLUMN "GROUP"."GROUP_OPEN" IS '공개(0), 비공개(1)(비공개시 비밀번호 필수)';

COMMENT ON COLUMN "GROUP"."GROUP_PWD" IS '그룹 비밀번호';

COMMENT ON COLUMN "GROUP"."GROUP_EXPLAIN" IS '그룹 설명';

COMMENT ON COLUMN "GROUP"."GROUP_IMG_PATH" IS '그룹 대표이미지 파일 위치';

COMMENT ON COLUMN "GROUP"."GROUP_IMG_NAME" IS '그룹 대표이미지 파일명';



CREATE TABLE "GROUP_MEMBER" (
	"GROUP_ID"	NUMBER		NOT NULL,
	"GROUP_MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "GROUP_MEMBER"."GROUP_ID" IS '그룹 아이디, SEQUENCE';

COMMENT ON COLUMN "GROUP_MEMBER"."GROUP_MEM_ID" IS '그룹회원 아이디';




ALTER TABLE "RECORD" ADD CONSTRAINT "PK_RECORD" PRIMARY KEY (
	"RECORD_ID",
	"RECORD_SUBJECT_ID",
	"RECORD_MEM_ID"
);

ALTER TABLE "SUBJECT" ADD CONSTRAINT "PK_SUBJECT" PRIMARY KEY (
	"SUBJECT_ID",
	"MEM_ID"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEM_ID"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_ID"
);

ALTER TABLE "BOARD_REPLY" ADD CONSTRAINT "PK_BOARD_REPLY" PRIMARY KEY (
	"REPLY_ID"
);

ALTER TABLE "GROUP" ADD CONSTRAINT "PK_GROUP" PRIMARY KEY (
	"GROUP_ID"
);

ALTER TABLE "GROUP_MEMBER" ADD CONSTRAINT "PK_GROUP_MEMBER" PRIMARY KEY (
	"GROUP_ID",
	"GROUP_MEM_ID"
);
-----컬럼과 매치되는 유니크나 프라이머리 키가 없다고 나옴 -> unique 설정
--ALTER TABLE SUBJECT
--add constraint SUBJECT_ID_UQ unique(SUBJECT_ID);
--ALTER TABLE SUBJECT
--add constraint MEM_ID_UQ unique(MEM_ID);


--복합 FK로 설정하고 unique 설정은 제외함 --> unique 설정 시 MEM_ID당 하나의 SUBJECT테이블만 생성됨
ALTER TABLE "RECORD" ADD CONSTRAINT "FK_SUBJECT_TO_RECORD_1" FOREIGN KEY (
	"RECORD_SUBJECT_ID","RECORD_MEM_ID"
)
REFERENCES "SUBJECT" (
	"SUBJECT_ID","MEM_ID"
);



--ALTER TABLE "RECORD" ADD CONSTRAINT "FK_SUBJECT_TO_RECORD_2" FOREIGN KEY (
--	"RECORD_MEM_ID"
--)
--REFERENCES "SUBJECT" (
--	"MEM_ID"
--);
---------------------
ALTER TABLE "SUBJECT" ADD CONSTRAINT "FK_MEMBER_TO_SUBJECT_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"BOARD_WRITER"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "BOARD_REPLY" ADD CONSTRAINT "FK_BOARD_TO_BOARD_REPLY_1" FOREIGN KEY (
	"BOARD_ID"
)
REFERENCES "BOARD" (
	"BOARD_ID"
);

ALTER TABLE "BOARD_REPLY" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_REPLY_1" FOREIGN KEY (
	"REPLY_WRITER_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "GROUP_MEMBER" ADD CONSTRAINT "FK_GROUP_TO_GROUP_MEMBER_1" FOREIGN KEY (
	"GROUP_ID"
)
REFERENCES "GROUP" (
	"GROUP_ID"
);

ALTER TABLE "GROUP_MEMBER" ADD CONSTRAINT "FK_MEMBER_TO_GROUP_MEMBER_1" FOREIGN KEY (
	"GROUP_MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

